/**
 * Wallet service.
 *
 * NOTHING IN THIS MODULE MOVES VALUE.
 *
 * Deposits, withdrawals and transfers are the points where a real platform
 * touches custody and the chain. In this prototype every one of them returns a
 * refusal that says plainly that no transaction occurred. Do not "simulate
 * success" here: a UI that reports a completed deposit which never happened is
 * indistinguishable from fraud to the person reading it.
 *
 * To make these real you need, at minimum: a custody provider or node
 * infrastructure, address generation and validation per network, withdrawal
 * allow-listing and approval, AML/sanctions screening, and an audited ledger.
 */

import { platform } from '../config'
import { demoWallets } from '../mock-data'
import type { ApiResult, WalletBalance } from '../types'
import { request, withCapability, withFallback } from './client'

export async function listBalances(): Promise<ApiResult<WalletBalance[]>> {
  return withCapability(
    platform.custodyEnabled,
    () => request<WalletBalance[]>('/wallet/balances'),
    // No custodian means no wallets exist — not wallets that happen to be empty.
    () => [],
    () => demoWallets,
  )
}

/** Outcome of any value-moving request. `completed` is never true in demo mode. */
export interface WalletActionResult {
  completed: boolean
  demo: boolean
  message: string
}

const DEMO_REFUSAL = (action: string): WalletActionResult => ({
  completed: false,
  demo: true,
  message: `Demo environment — no ${action} was made and no funds moved. Connect a custody backend to enable this.`,
})

/**
 * Deposit addresses must be generated by the custody backend and shown only
 * after it returns one. Never display a placeholder string that looks like an
 * address: someone will send funds to it.
 */
interface DepositAddress {
  /** Null until a custody backend returns a real, funded-safe address. */
  address: string | null
  network: string | null
  demo: boolean
}

export async function getDepositAddress(
  assetId: string,
  network?: string,
): Promise<ApiResult<DepositAddress>> {
  return withFallback(
    () =>
      request<DepositAddress>(`/wallet/deposit-address/${assetId}`, { query: { network } }),
    () => ({ address: null, network: network ?? null, demo: true }),
    350,
  )
}

export async function requestDeposit(
  assetId: string,
  amount: number,
): Promise<ApiResult<WalletActionResult>> {
  return withFallback(
    () => request<WalletActionResult>('/wallet/deposits', { method: 'POST', body: { assetId, amount } }),
    () => DEMO_REFUSAL('deposit'),
    450,
  )
}

export async function requestWithdrawal(
  assetId: string,
  amount: number,
  address: string,
): Promise<ApiResult<WalletActionResult>> {
  return withFallback(
    () =>
      request<WalletActionResult>('/wallet/withdrawals', {
        method: 'POST',
        body: { assetId, amount, address },
      }),
    () => DEMO_REFUSAL('withdrawal'),
    450,
  )
}

export async function requestTransfer(
  assetId: string,
  amount: number,
  destination: string,
): Promise<ApiResult<WalletActionResult>> {
  return withFallback(
    () =>
      request<WalletActionResult>('/wallet/transfers', {
        method: 'POST',
        body: { assetId, amount, destination },
      }),
    () => DEMO_REFUSAL('transfer'),
    450,
  )
}
