/**
 * FAQ content.
 *
 * Kept in a plain module rather than alongside the accordion component: the
 * accordion is a client component, and values exported from a `'use client'`
 * file reach server components as client references, not as data. Server pages
 * (and the JSON-LD builder) need the real array, so it lives here.
 *
 * Answers are plain strings so the same text can be emitted as structured data
 * without the markup and the schema drifting apart.
 */

export interface FaqItem {
  question: string
  answer: string
}

export const faqItems: FaqItem[] = [
  {
    question: 'What is the platform?',
    answer:
      'Nexora is a digital asset platform for following markets, managing a portfolio and trading supported assets. This build is a demonstration environment: the prices, balances and transactions you see are sample data, and no real funds or orders are involved.',
  },
  {
    question: 'How do I create an account?',
    answer:
      'Choose Create Account, enter your name, email and a password, and accept the terms. You will then be asked to confirm your email address before continuing.',
  },
  {
    question: 'How does verification work?',
    answer:
      'Identity verification (KYC) is required before you can deposit, withdraw or trade. You will be asked for government-issued identification and proof of address. The exact documents and processing times depend on your jurisdiction and will be confirmed by the operator before launch.',
  },
  {
    question: 'What assets are supported?',
    answer:
      'The demonstration build shows Bitcoin, Ethereum, Solana, BNB, XRP and Tether. The final list of supported assets, and the networks each can be sent over, is set by the operator.',
  },
  {
    question: 'How do deposits work?',
    answer:
      'Once verification is complete you will be given deposit details for the asset and network you choose. Deposit addresses are generated by the custody provider — this build does not display one, because an address shown before that integration exists could lead to a permanent loss of funds.',
  },
  {
    question: 'How do withdrawals work?',
    answer:
      'You submit a withdrawal request with a destination address and amount. Requests are subject to security checks, withdrawal controls and network confirmation times. Withdrawals are not enabled in this demonstration build.',
  },
  {
    question: 'What fees apply?',
    answer:
      'The fee schedule — trading fees, deposit and withdrawal costs, and any plan fees — is set by the operator and has not yet been supplied. It will be published in full on the Pricing page before launch. Fees reduce your returns.',
  },
  {
    question: 'How is my account protected?',
    answer:
      'The platform provides password authentication, two-factor authentication, active session management and a login history so you can see where your account has been accessed. Specific infrastructure and custody arrangements will be documented on the Security page once finalised.',
  },
  {
    question: 'What are the risks of cryptocurrency?',
    answer:
      'Digital assets are highly volatile and can lose value quickly, including all of it. They are largely unregulated in many jurisdictions, so protections that apply to bank deposits or regulated investments may not apply. Transactions on a blockchain are generally irreversible, and assets can be lost permanently through error or theft. Never invest money you cannot afford to lose.',
  },
  {
    question: 'How do I contact support?',
    answer:
      'Use the contact form on the Contact page. Published support channels and response times will be confirmed by the operator before launch.',
  },
]
